[profile.default]
solc_version = "0.8.20"  # Specify the correct Solidity version
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts"]
ffi=true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
